'use client';

import { Metadata } from 'next';
import { Inter } from 'next/font/google'
import { css } from '@emotion/react';

import './globals.css';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] });
const rootLayout = {
  header: css({
    width: '100%',
  }),
  main: css({
    height: 'calc(100% - 54px)',
  }),
  logo: css({
    objectFit: 'contain',
  })
};

export const metadata: Metadata = {
  title: 'Recognition Program',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className} >
        <header css={rootLayout.header}>
          <Image 
            src='/logo.png' 
            width={120} 
            height={50} 
            css={rootLayout.logo} 
            alt="liferay-logo"
          />
        </header>
        <main css={rootLayout.main}>
          {children}
        </main>
        </body>
    </html>
  )
}
