'use client';

import { css } from '@emotion/react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { QueryClientProvider } from '@tanstack/react-query';
import Image from 'next/image';
import queryClient from '../lib/queryClient';
import './globals.css';
import LayoutHeader from '../components/LayoutHeader';

const inter = Inter({ subsets: ['latin'] });
const rootLayout = {
  header: css({
    width: '100%',
    padding: '5px 20px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between'
  }),
  main: css({
    height: 'calc(100% - 64px)',
  }),
  logo: css({
    objectFit: 'contain',
  }),
};

export const metadata: Metadata = {
  title: 'Recognition Program',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
        <title>Recognition Program</title>
      </head>
      <body className={inter.className} suppressContentEditableWarning>
        <header css={rootLayout.header}>
          <Image 
            src='/logo.png' 
            width={120} 
            height={50} 
            css={rootLayout.logo} 
            alt="liferay-logo"
          />
          <LayoutHeader />
        </header>
        <QueryClientProvider client={queryClient}>
          <main css={rootLayout.main}>
            {children}
          </main>
        </QueryClientProvider>
        </body>
    </html>
  )
}
